# Generated by Django 3.1.3 on 2020-11-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandises', '0005_auto_20201115_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='on_stock',
            field=models.BooleanField(default=True),
        ),
    ]
