# Generated by Django 3.1.3 on 2020-11-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20201117_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='merchant_email',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price_dec',
        ),
    ]
