# Generated by Django 3.1.3 on 2020-11-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='merchant',
            field=models.CharField(max_length=80),
        ),
    ]
