# Generated by Django 3.1.3 on 2020-11-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20201118_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='merchant',
            field=models.IntegerField(default=0),
        ),
    ]
