# Generated by Django 3.1.3 on 2020-11-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20201118_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='merchant',
            field=models.CharField(max_length=20),
        ),
    ]
