# Generated by Django 3.1.3 on 2020-11-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20201118_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_price',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_price_dec',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
