# Generated by Django 3.1.3 on 2020-11-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20201118_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='on_stock',
            field=models.BooleanField(default=True),
        ),
    ]
