# Generated by Django 3.1.3 on 2020-11-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_purchased_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchased_item_slug',
            field=models.SlugField(default='', editable=False, max_length=90),
        ),
    ]
