# Generated by Django 3.1.3 on 2020-11-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_remove_purchase_purchased_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='on_stock',
            field=models.BooleanField(default=False),
        ),
    ]
