# Generated by Django 3.1.3 on 2020-11-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_purchase_on_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchased_item_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
