# Generated by Django 3.1.3 on 2020-11-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_purchase_purchased_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='buyer_username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
