# Generated by Django 3.1.3 on 2020-11-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_purchase_buyer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchases_price_dec',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
