# Generated by Django 3.1.3 on 2020-11-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_purchase_purchases_price_dec'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='buyer_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
