# Generated by Django 3.1.3 on 2020-11-25 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_purchase_buyer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='buyer_email',
        ),
    ]
