# Generated by Django 3.1.3 on 2020-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initial',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
