# Generated by Django 3.1.3 on 2020-11-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_auto_20201109_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initial',
            name='total',
        ),
    ]
