# Generated by Django 3.1.3 on 2020-11-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0003_remove_initial_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='initial',
            name='name',
            field=models.CharField(default='init', max_length=255),
        ),
    ]
