# Generated by Django 3.1.3 on 2020-11-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_image',
            field=models.URLField(blank=True, default='https://via.placeholder.com/90', max_length=255),
        ),
    ]
