# Generated by Django 3.1.3 on 2020-11-13 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20201113_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_dec',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=53)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[-,0-9]+$', 'Only numbers and commas are allowed.')]),
        ),
    ]
