# Generated by Django 3.1.3 on 2020-11-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20201113_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_image',
            field=models.URLField(blank=True, default='https://via.placeholder.com/150', max_length=255),
        ),
    ]
