# Generated by Django 3.1.3 on 2020-11-14 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0007_auto_20201115_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(default=({'email': 'agimperialpgc@gmail.com', 'password': 'argon2$argon2i$v=19$m=512,t=2,p=2$eEFEVzlpb3NNVVd3$iZVkzDES5i4rB5QINvUiGw', 'pk': 2, 'username': 'destroyer8'},), on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
